### ISSUE TITLE
Code fragmenting not correctly applied to code-block

### ISSUE THREAD

**Issue by nilsramsperger** [gitpitch/gitpitch#136] opened 2017-11-22 18:45 UTC
Hello,

I'm trying to get code fragmenting work properly for a presentation. On some slides the fragments are not properly applied to the code block. I am not sure, if I did the markup right, but I can't find any mistake.
See the reproducer at https://gitpitch.com/nilsramsperger/vortrag-docker/dev#/
The behaviour can be seen on Firefox, Chrome and Safari.
A Bug, or just me?

Greetings
Nils

**Comment by gitpitch** [comment] 2017-11-23 03:27
Hi @nilsramsperger thanks for reporting this issue. The problem here is that your code block has has not specified a **code language hint** and your shell commands are being incorrectly identified as `dockerfile` content (because `docker` appears repeatedly in the content). 

What you need to do is simply add a code language hint on your code block(s). For example:

<img width="337" alt="docker-as-shell" src="https://user-images.githubusercontent.com/19169584/33157712-9ec8c25e-d036-11e7-974f-7aa3a3877421.png">

Note the addition of the word `shell` immediately following the opening triple backticks for your static code block.

You can learn more about [code language hints here](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides#code-highlighting-language-hint). I have also just updated the [Code Block](https://github.com/gitpitch/gitpitch/wiki/Code-Slides) page on the Wiki to include a note about the use of code language hints.

Hopefully this will fix your problem. If you have a chance to test can you please update or close out this thread as appropriate.

**Comment by nilsramsperger** [comment] 2017-11-23 15:58
Hello,

Thanks for the fast reply.
I just set language-hints for all my codeblocks and it worked with one exception.
One block is hinted with "Dockerfile". There the problem persists. According to the languages list on highlightjs.org it should be correct.
Using "dockerfile" instead makes no difference.

I updated the reproducer at https://gitpitch.com/nilsramsperger/vortrag-docker/dev#/

**Comment by gitpitch** [comment] 2017-11-26 03:57
Thanks for this update, much appreciated. I've looked into this and there is definitely an incompatibility as you reported when `dockerfile` is in use. Until I have a solution to that problem I suggest you use `text` or `shell` as the lang hint on any `dockerfile` blocks that you are using. It will cause your Dockerfile content to render somewhat plainly, but code-presenting within your slides will be fully functional.

**Comment by nilsramsperger** [comment] 2017-11-26 17:39
Thanks for the info. I will switch to `bash` as a workaround untill a fix is available.

**Comment by gitpitch** [comment] 2020-01-26 13:20
Update on thread. Dockerfile [code syntax highlighting language hint](https://gitpitch.com/docs/code-features/fenced-blocks/#the-importance-of-code-language-hints) is now cleanly supported. For example, the sample slide now renders as follows:

![highlighting-dockerfile](https://user-images.githubusercontent.com/19169584/73135758-af541d80-4078-11ea-9a43-b5b9ec7c7dbb.png)

This looks good to me. Closing issue as resolved. Feel free to reopen issue if you find a reproducible test case.

**Closed by gitpitch** 2020-01-26 13:20 UTC
