### ISSUE TITLE
Unable to print

### ISSUE THREAD

**Issue by steverice** [gitpitch/gitpitch#21] opened 2016-11-02 21:20 UTC
Hi @gitpitch, I'm having trouble printing https://gitpitch.com/steverice/pagerduty-api-v2-deck. I end up with a 200 response with the right `application/pdf` type, but the browser just keeps loading the PDF without ever finishing.

I have to imagine that the request is timing out, given it is a larger presentation. I try to print with gitpitch running locally buy I get this error:
```
GitPitch Slideshow print service temporarily unavailable.
```

A quick look at the code suggests this just means there was a general error with the printing functionality, but I don't see anything of note in the `/logs` directory. Any tips on how to debug this? I'm thinking there's some config I could tweak in my local instance to increase the timeout, but I'm not sure where to get started.

**Comment by steverice** [comment] 2016-11-03 01:37
Seems like it did eventually finish printing. Not quite the same CSS but I can live with that.
But I'm still curious what the issue might be with my local setup and how I could fix it.

**Comment by gitpitch** [comment] 2016-11-03 03:16
Hi @steverice 

So yes, even if your browser connection to the server timeouts out waiting for the print job to complete the actual printing in the backend will complete. This explains why if you hit reload in your browser after an apparent print failure you will often see the generated PDF almost instantly.

As for a quick config tweak, you could try updating your `conf/application.conf` by adding the following `timetout` configuration:

```
play.ws {

    timeout {
        connection = 300000
        idle = 300000
        request = 300000
    }
...
``` 

Note, all you need to add here is the `timeout` block inside of `play.ws`. The `play.ws` block already exists in your `conf/application.conf` file, I'm just showing it here for context. By altering these timeouts, in this case increasing above the defaults, your local server should be more forgiving of longer idle time on connections (such as print connections).

I have not yet had a chance to test on my own staging servers but hopefully this is something you can test quickly yourself, just make the config change, build, and redeploy. I will do my own testing later today but if you have a chance to test this locally please let me know how you get on.

As a final observation, while I was debugging this printing issue I noticed that your presentation uses custom CSS and your custom CSS declares a  number of dependencies on local fonts, for example:

```
@font-face {
  font-family: 'Colfax';
  src: url('../fonts/ColfaxWebMedium.eot');
  src: url('../fonts/ColfaxWebMedium.woff') format('woff');
  font-weight: bold;
  font-style: normal;
}
```

These fonts live in your `assets/fonts` directory within your repo. But given GitPitch only parses and processes your Markdown (and not your CSS) these relative paths will be invalid when your presentation is rendered in your browser. Doing a quick inspection using Dev Tools in the browser verifies this:

![pagerduty-fonts](https://cloud.githubusercontent.com/assets/19169584/19954568/bcf791b6-a1ab-11e6-8973-8d51c9ed3abd.png)

The problem here is simple, the browser expects to load the fonts from a path relative to the page currently being rendered (your presentation) while the actual relative path is really to a file in your GitHub repo.

The seemingly obvious solution should be to use absolute paths in your CSS. And if you want the absolute path to a GitHub file you need to use its `raw` URL. For example, for the following file:

```
assets/fonts/ColfaxWebRegular.woff
```

The absolute (raw) URL is as follows:

```
https://github.com/steverice/pagerduty-api-v2-deck/raw/master/assets/fonts/ColfaxWebRegular.woff
```

But I was just doing a little reading about `font-face` and absolute URLs and I came across the following:

> You can’t use @font-face in Firefox with a font hosted on a different domain If you want to specify a font for @font-face using an absolute URL, or a font hosted on a different domain, it needs to be served with Access Control Headers, specifically the Access-Control-Allow-Origin header set to '*' or the domains allowed to request the font.

I gather this is a security measure. And GitHub raw files are **definitely not** served with the required headers. So if you really want to use custom fonts with your GitPitch presentation it seems like you will have to point at a server serving fonts that is configured to return the appropriate headers. This could be your own server or a third part font server like Google Fonts.

I realize that this discussion of fonts is a little off topic but I hope it is still of some use to you.

**Comment by gitpitch** [comment] 2016-11-03 06:07
@steverice now that I've had some time to look into this here's an update.

It looks like the root cause of the `...temporarily unavailable` message is a timeout between the front end http server (nginx) and the upstream (or backend) proxied GitPitch server. This timeout occurs pretty consistently after 30s. I have yet to find a valid configuration that will prevent this timeout but I'm working on it.

I also need some additional info from you. You mentioned your local GitPitch server. On what OS have you deployed your server? And is your local GitPitch server proxied behind a front end http server? If so, which http server? Thanks.

**Comment by steverice** [comment] 2016-11-03 08:46
Completely appreciated off-topic discussion on fonts! I hadn't run into the font issue until I tried to print from gitpitch.com, as I have those fonts installed locally on my machine. Made some updates as you suggested.

The printing problem was actually quite straightforward after I noticed that errors were being printed to `stderr` and not a logfile. I was getting this:
```
java.io.IOException: Cannot run program "./bin/phantomjs" (in directory "../decktape"): error=2, No such file or directory
```
because I'd never set up decktape or phantomjs! I just followed the [decktape setup instructions](https://github.com/astefanutti/decktape#install), placing the `decktape` directory at the same level as `gitpitch` (as [specified in the configuration](https://github.com/gitpitch/gitpitch/blob/b0c992f9cc58d9ce006303b78edc5be9be4e1664/conf/application.conf#L371-L373)) and moved the `phantomjs` binary into a `bin` directory inside `decktape` [as specified by the code](https://github.com/gitpitch/gitpitch/blob/b0c992f9cc58d9ce006303b78edc5be9be4e1664/app/com/gitpitch/services/PrintService.java#L191).

After that, it's all working — plus I get nice progress output to `stdout` as the PDF renders. Perhaps you could add some brief instructions on `decktape`/`phantomjs` to the [server build instructions](https://github.com/gitpitch/gitpitch/wiki/Server-Build-Instructions)?

For the record, I'm running this on OS X (10.11) straight with `sbt run`, no proxy.

**Comment by gitpitch** [comment] 2016-11-05 05:15
@steverice glad the fonts tip was useful.

The Wiki is indeed lacking important info for enabling printing on a local server, good catch and thanks for pointing this out. The Wiki has been updated to fill in the gaps, [see here](https://github.com/gitpitch/gitpitch/wiki/Server-Build-Instructions).

Great to hear it's now all working as expected for you there. This issue has also helped me identify a config problem governing the interact between nginx and the upstream production server on [GitPitch.com](https://gitpitch.com). A fix is still a work-in-progress but it's being worked. Thanks again.

**Closed** 2016-11-08 10:32 UTC
