### ISSUE TITLE
CRLF lost when copying code fragment (in Firefox and IE)

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#82] opened 2017-06-14 20:59 UTC
The following presentation demonstrates this issue.

https://gitpitch.com/terrywbrady/tbDemo/gitpitch

Is there a work-around you could suggest?

**Comment by gitpitch** [comment] 2017-06-15 14:08
Hi @terrywbrady is this a regression, was this working for you before? It may be caused by some of the changes I made to support the new [code-presenting](https://github.com/gitpitch/gitpitch/wiki/Code-Presenting) functionality. And if so there may be a simple fix, using explicit [language hints](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides#code-highlighting-language-hint) for your code blocks and code delimiters. What language are you using in your presentation, it looks like plain text or maybe csv, I can't tell for sure?

But first I'd like to ask you to try something for me which will help us understand where the problem is coming from. Can you please open the following [demo presentatation](https://gitpitch.com/gitpitch/code-presenting/reveal-3.4.1) and try to copy code fragments from both slides using code-blocks and slides using code-delimiters. And then let me know how you get on. Thanks.

**Comment by terrywbrady** [comment] 2017-06-15 15:26
@gitpitch ,

I see the same behavior in your demo presentation.  The EOLs are preserved in Chrome but not in Firefox or IE.  I do believe that this process worked for me in the past in Firefox.  It has been a couple months since I used the presentation that relied on the code copying functionality.

I tried a variety of lang settings with my CSV data, and changing the lang did not seem to help the EOLs.

Let me know if you have something that you would like for me to test.

Terry

**Comment by gitpitch** [comment] 2017-06-15 15:44
@terrywbrady I've tested your sample presentation and my own demo presentation on Chrome and Safari and all worked fine. But I can reproduce the problem you reported on Firefox. I don't have access to IE.

I do not have any solution or workaround for you on Firefox or IE.

**Comment by terrywbrady** [comment] 2017-06-19 20:23
@gitpitch , thanks for the follow up on this.

I can avoid using Firefox when I give this presentation, but for folks who view the presentation it may not be apparent that copy/paste may not work across browsers.  

Would it be possible to provide a hyperlink citation to the raw code file when displaying a code fragment?  This would allow a presentation view to retrieve a source file with line breaks.

I attempted to fix this behavior by applying some custom CSS rules, but I had no luck.  I wonder if the span.line elements that are now present in each line of code are causing Firefox to drop the whitespace characters between lines.

**Comment by gitpitch** [comment] 2017-06-23 02:34
Hi @terrywbrady I've been looking into this and the problem is definitely caused by how I am handling end-of-line characters within recent changes to support the code-presenting feature. I'm still not sure why this exhibits in some browsers but not others. I do not have a fix or workaround for you right now but it's on my to-do list.

I'm honestly not convinced it makes sense for GP to auto-inject a citation link to the raw source file in every presentation but it is certainly something you can add easily to your own presentations if needed.

**Comment by gitpitch** [comment] 2020-06-06 09:43
Closing issue. Please re-open if issue remains.

**Closed by gitpitch** 2020-06-06 09:43 UTC
