### ISSUE TITLE
Slide-Specific Transitions produce weird hybrid transition effects

### ISSUE THREAD

**Issue by joachim-n** [gitpitch/gitpitch#196] opened 2018-07-29 19:14 UTC
I have a presentation that is set to use the default 'slide' transition. Within that, I want two slides that have no transition effect between them.

My assumption was that the '@transition[none]' override controls one transition. However, it appears to control *half* of the two transitions either side of the slide that has the override.

This means that:

- going from the slide before to the overridden slide produces an effect where the first slide  contents slide away and the overridden slide contents just appear. Not the desired effect.
- going from the overridden slide to the next slide, the overridden slide contents vanish and the next slide contents slide in.

If I set the override on TWO consecutive slides, I get the desired effect between them. But then I get the ugly hybrid effect either side of those!

Demo here: https://gitpitch.com/joachim-n/git-pitch-demo/master

**Comment by gitpitch** [comment] 2018-07-30 03:16
I will need to look into this further when time permits but here is a suggestion that you can try out and let me know how it goes:

When specifying your custom transitions for individual slides you can set both an `in` and an `out` transition for the slide. For example:

```
@transition[none slide]
```

Another example:

```
@transition[none none]
```

You may be able to get the transition behavior you want for all of your slides by using an appropriate combination of custom and default transition settings.

If no combination gives you want you need, you might want to consider setting the [global transition setting](https://gitpitch.com/docs/settings/transition/) to `none`.

**Comment by joachim-n** [comment] 2018-07-30 12:53
Specifying the in and out transition is working great - just what I was after!

That could really do to be added to the docs -- https://gitpitch.com/docs/markdown-features/shortcuts#set-slide-specific-transition doesn't mention that at all.

**Comment by gitpitch** [comment] 2018-07-30 13:57
Glad it gave you what you needed. Good suggestions on updating the docs too. This is really a reveal.js feature but I will add a note to my own docs to help people discover the feature. 

Before we close this issue thread, do you mind sharing a snippet of your updated **PITCHME.md** on the thread, a snippet that demonstrates how you are now setting your transitions. It will make this thread more useful to other users that come upon this in the future. Thanks.

**Comment by DesHorsley** [comment] 2018-07-30 15:12
I've noticed something similar, if you have an image as a background at the top level, and turn off transitions if you navigate down to a vertical slide, the image will transision off the top of the page. 

Is that expected behavior? 

Example:
```
---?image=assets/example.jpg
# Top Level slide
@transition[none none]
+++
@transition[none none]
# Vertical slide
```

**Comment by gitpitch** [comment] 2018-07-30 15:18
@DesHorsley if I understand correctly what you are describing it is because background image transitions are distinct from the standard slide transitions.

If you want to disable transitions for background images try setting the `transition` query parameter on the background image delimiter to `none`. For example:

```
---?image=assets/example.jpg&transition=none
# Top Level slide
@transition[none none]
+++
@transition[none none]
# Vertical slide
```

If you try it out let me know if it is addressing the issue you mentioned.

**Comment by DesHorsley** [comment] 2018-07-30 15:35
Right on the money again, thanks @gitpitch fantastic support.

**Comment by gitpitch** [comment] 2018-08-02 07:57
To address the gap in the docs identified on this thread I have just updated the [transition shortcut syntax](https://gitpitch.com/docs/markdown-features/shortcuts#set-slide-specific-transition) docs to reflect the use of custom *slide-in* and *slide-out* transitions on individual slides.

**Closed by gitpitch** 2018-08-02 07:57 UTC
