### ISSUE TITLE
Elements overflowing slide

### ISSUE THREAD

**Issue by miguescri** [gitpitch/gitpitch#66] opened 2017-05-01 23:18 UTC
I've encountered problems with elements, such as vertical images and tables, going through the lower limits of the slide and, therefor, being imposible to be seen in any way. Worst thing is, when I try to print the pitch as PDF, those elements that were invisible at the slide now overflow the next one.

I see two solutions:

- Code snippets handle overflow in a nice way, allowing you to **scroll both vertical and horizontaly**; maybe you could make this the default behaviour when contents are bigger than slide, or include a special **syntax to force that**.
- Markdown doesn't provide tools itself to handle size of images (AFAIK and not including HTML), so it would be nice to **automatically resize** elements so they can fit inside the slide, or include a special **syntax to force that**.

**Comment by ahangchen** [comment] 2017-05-02 11:36
I think this is caused by that max-height for the image is not working.

**Comment by Nastybastard** [comment] 2017-05-02 14:54
They fixed it

**Comment by gitpitch** [comment] 2017-05-02 23:00
Do you mean it has been fixed in reveal.js? If so, in what release?

**Comment by miguescri** [comment] 2017-05-02 23:08
I had those problems yesterday night. Has there been a fix since then?

*Miguel Escribano*

2017-05-03 1:00 GMT+02:00 David Russell <notifications@github.com>:

**Comment by gitpitch** [comment] 2017-05-02 23:15
There have been updates yesterday to GP but nothing that should affect image rendering. If anyone has a presentation that is still experiencing problems rendering images can you please provide links here on this thread so I can investigate. Thanks.

**Comment by miguescri** [comment] 2017-05-02 23:48
Seems like something has changed, because now some of my images resize
properly, but other doesn't.

https://gitpitch.com/miguescri/dummy/master?grs=gitlab&t=white

*Miguel Escribano*

2017-05-03 1:15 GMT+02:00 David Russell <notifications@github.com>:

**Comment by ahangchen** [comment] 2017-05-03 00:45
@gitpitch https://gitpitch.com/ahangchen/slides/master 
As shown in the above Slides in page 5, my image is overflow vertically.
and in page7, my sentences are overflow horizontally in full screen mode.
It seems that the whole slides has somewhere setting larger left margin than right margin.

**Comment by gitpitch** [comment] 2017-05-03 01:34
@miguescri and @ahangchen I have created PRs for both of your presentation repos, updating your presentation markdown and configuration to use [slide background images](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background) and the [background setting](https://github.com/gitpitch/gitpitch/wiki/Background-Setting) which lets you take control of image scaling on your slides.

As for the text overflow issue, it appears to only occur when I switch from normal viewing mode to fullscreen. I do not know why. For now I suggest you refactor your text into more concise bullet points.

**Comment by ahangchen** [comment] 2017-05-03 04:44
For the image vertical overflow, now most of the image can be presented, but it's still a little larger than the screen.

For the text overflow, although it seems OK in normal mode, but look at the page 1, you can notice the left margin of the title is larger than right margin. The title is not strictly in the center of the page. I think this is the reason and this point will be magnified in full screen mode.

**Comment by gitpitch** [comment] 2017-05-03 07:39
If your image is still overflowing when using background images with auto-scale the next thing you can try resizing it the image, reducing it's width/height proportionally by 15% or 20%.

As for text overflow, I have not had time to test but are you sure your own custom css is not causing the title to be rendered off center?  A simple test would be to disable the `theme-override` property in your presentation `PITCHME.yaml` and see if the title then centers without it. Let me know what you learn. And remember, if you are developing your presentation in your master branch you will be subject to 180 seconds caching before you see your latest changes. See [GitPitch Caching Policy](https://github.com/gitpitch/gitpitch/wiki/GitPitch-Caching) for details.

**Comment by ahangchen** [comment] 2017-05-03 13:50
I find that the style of the class slide set left 50% and right auto. When I set 

```css
.reveal .slides {		
    padding: 2em;		
 }
```

The title is not in the center. Now I remove this attribute and get a fine result. But I need to try other attribute for custom slides padding.

**Comment by gitpitch** [comment] 2017-05-03 14:29
Can you please clarify, was the off center alignment problem that you originally reported caused by some conflict between the base theme and your own custom css? I would like to clearly understand the issue as best I can. Thanks.

**Comment by ahangchen** [comment] 2017-05-03 15:32
I think it's cause by the conflict between this attribute

```css
.reveal .slides {		
    padding: 2em;		
 }
```

and the moon theme.

**Comment by gitpitch** [comment] 2017-05-03 16:12
@ahangchen a worthwhile test you can try is to revert back to using revealjs v3.3.1 by updating the property in your `PITCHME.yaml` file as follows:

```
# revealjs: 3.4.1
```
Note, I've simply commented out the revealjs property which will cause your presentation to be rendered by the default revealjs version, which is `3.3.1`. If there is a conflict as you described it may have crept into the 3.4.1 release. Please let me know what you see if you run this quick test.

**Comment by ahangchen** [comment] 2017-05-04 10:54
Commenting the revealjs property doesn't work. Actually, I have this problem before your PR on revealjs property for the image overflow problem.

**Comment by lukehsiao** [comment] 2017-06-06 05:52
I'm seeing this problem as well for vertical images. Is there any way to implement the scaling options that are available for background slides for normal image slides?

**Comment by gitpitch** [comment] 2017-06-06 06:53
@lukehsiao can you please provide a link to your presentation and indicate each slide where you are experiencing a rendering problem. Thanks.

**Comment by lukehsiao** [comment] 2017-06-06 07:29
@gitpitch Slide 3 found here: https://gitpitch.com/jervisfm/rebbr/dev

**Comment by gitpitch** [comment] 2017-06-06 16:28
@lukehsiao thanks for the link.

The image on your 3rd slide is taller than it is wide which gives it the opposite aspect ratio to the slides in your presentation which is wider than they are tall. This is the root cause of your rendering issue.

**Recommended Approach:**

To overcome this problem you will will have to force your image to be `contained` within your slide by using the `background-size` setting in your `PITCHME.yaml` file, as follows:

```
background-size : contain
```
You will then need to use a [background image delimiter](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background) to load your image into your slide:

```
---?image=http://deliveryimages.acm.org/10.1145/3030000/3022184/vanjacobson1.png
```

**Alternate Approach:**

If you do not want to change image scaling to `contain` for all sides you can remove `background-size` from your `PITCHME.yaml` file and then directly embed a HTML comment in the following format at the start of your slide:

```
---

<!-- .slide: data-background-image="http://deliveryimages.acm.org/10.1145/3030000/3022184/vanjacobson1.png" data-background-size="contain" -->
```

This will give you same result as if you used the `background-size` property and the background-image delimiter. While this works, this syntax/approach is not as clean or obvious.

**Finally, in answer to your question:**

> Is there any way to implement the scaling options that are available for background slides for normal image slides?

Currently there is not. Simply because what you call normal image slides use standard Markdown image syntax which does not provide any way to specify scaling preferences. Adding an extension at some point is something I might well consider but no such extension exists today.

**Comment by lukehsiao** [comment] 2017-06-06 17:17
Thanks for the thorough answer and quick responses!

**Comment by lukehsiao** [comment] 2017-06-06 17:32
Can you point me to the wiki page which discusses how to use the `background-position` option? I see it mentioned on the [Background Setting](https://github.com/gitpitch/gitpitch/wiki/Background-Setting) page, but don't see how it is used.

**Comment by terrywbrady** [comment] 2017-06-06 18:18
Adding to this thread, I would find it handy to have the background-size setting honored in full screen mode.  See slide 2.6 of https://gitpitch.com/terrywbrady/tbDemo/test.  Ideally, I would like to set background-size to either auto or contain provided the setting would also apply in full screen mode.

**Comment by lukehsiao** [comment] 2017-06-06 20:15
@gitpitch: while the background workaround works for the vertical image in the slideshow, when a PDF is generated, the image on slide 3 is no longer correctly scaled and bleeds off of the edges of the slide. Is there a way to fix this?

**Comment by gitpitch** [comment] 2017-06-07 03:03
@lukehsiao the `background-size` option in your `PITCHME.yaml` file allows you to control the [background-size css property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) on your background images.

As you can see if you follow [the link](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) to the css docs this property gives you a lot of control on how your image is rendered. Using the `two-value` (width & height) syntax for this css property you can create a margin around your image by saying use just 95% or 90% of the space available. 

For example, here is your image rendered using 100% of available screen space (zero margin) which is the default for background images:

![100](https://user-images.githubusercontent.com/19169584/26860391-eca8d7e2-4b67-11e7-9b77-1a058c784a0b.png)

Here it is again using 95% of available screen space (effectively a 5% margin):

![95](https://user-images.githubusercontent.com/19169584/26860397-f4eb9b9c-4b67-11e7-943f-3fc546ec711c.png)

And here it is again using 90% of available screen space (effectively a 10% margin):

![90](https://user-images.githubusercontent.com/19169584/26860402-fb5fef82-4b67-11e7-88ab-a0816b64b427.png)

In your `PITCHME.yaml` file you do that as follows:

```
background-size : "90% 90%"
```

As GitPitch auto-centers your image the effect is a 10% margin all around your image on the slide.

I can definitely do a better job of documenting this on the Wiki. I will try getting around to updating the docs sooner rather than later.

@terrywbrady I've looked at your presentation and the slide you indicated. What exactly is the problem you are seeing between normal and fullscreen mode? It looks the same (correct) to me, what am I missing?

**Comment by gitpitch** [comment] 2017-06-07 04:51
Quick update for anyone following this thread and interested in how to scale or size images within a given slide in a GitPitch presentation.

I've just pushed new support (live on gitpitch.com) for custom scaling/sizing when working with [background image slide delimiters](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#background).

A new `size` parameter can be specified on the `---image?=` delimiter as follows:

```
---?image=path/to/image.file&size=custom-size-config
``` 

Where `custom-size-config` can take any value that is valid on the [background-size css property](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size). For example, `auto`, `contain`, `cover`, `90% 90%` etc. The default value for all backgrond images if left unspecified is `100% 100%`.

With this new feature you can now take control of image scaling/sizing on a **per-slide basis**. This can be very useful when you are using image assets that do not share a common aspect-ratio with each other (or with the overall presentation layout) which is something that has been the root cause of rendering issues for numerous people on this thread. With this new support, these issues can now be easily handled directly within `PITCHME.md` markdown.

See the following [sample presentation for a live demonstration](https://gitpitch.com/gitpitch/feature-demo/customize-image-size) of custom image scaling/rendering on a per-slide basis. 

The [background-size property](https://github.com/gitpitch/gitpitch/wiki/Background-Setting) is still available to you in your `PITCHME.yaml` config. That value is still applied globally on every slide. However if you have specified a `&size=` config on individual slides then that custom slide-specific sizing is used on those slides (as it overrides the global config).

I still need to update the official Wiki docs but this should be enough information to help you start taking more control over the rendering of your images.

**Comment by lukehsiao** [comment] 2017-06-07 07:05
@gitpitch Fantastic! Thanks!

**Comment by terrywbrady** [comment] 2017-06-07 15:35
@gitpitch , this sounds like a great option.  I am eager to experiment with this as I enhance my presentation.  Thank you.

**Comment by gitpitch** [comment] 2017-06-08 01:56
The wiki has been updated to reflect the new image sizing and scaling support, [see here](https://github.com/gitpitch/gitpitch/wiki/Image-Slides#slide-image-sizing--scaling).

Closing this issue as resolved.

**Closed by gitpitch** 2017-06-08 01:56 UTC

**Comment by gitpitch** [comment] 2017-09-12 15:04
Hi @fladd can you share a link to your sample presentation where you are experiencing table rendering problems when printing? Is the problem reproducible both (1) when printing on the server and (2) when printing in the browser? These two printing options are described [here](https://github.com/gitpitch/gitpitch/wiki/Slideshow-Printing).

**Comment by fladd** [comment] 2017-09-12 16:44
@gitpitch It is not about printing necessarily, but about automatic scaling of (large) tables, such that they fit on a slide. I tried wrapping it into html in order to change the font size for just the table, but it seems that markdown within html is not interpreted.

**Comment by gitpitch** [comment] 2017-09-13 02:05
Thanks for the additional feedback @fladd. So GitPitch makes no attempt to fit general content into a slide. Your content simply has to fit within the normal resolution of the presentation. I currently see no way change this as this is a core behavior of the underlying slide rendering engine, reveal.js.

However, images are a clear exception to this rule. Given this, if you capture a screenshot of your large data table you could then use the image scaling feature (described above) to render your entire table on a single slide. This is my best and unfortunately only recommendation at this time.
