### ISSUE TITLE
Figures in @snap layouts change size when saving to offline pdf

### ISSUE THREAD

**Issue by mrava87** [gitpitch/gitpitch#213] opened 2018-08-31 11:41 UTC
Hi,
I have the following piece of code that is creating a page with 3 figures aligned horizontally and the result is as expected in the online mode (both on Chrome and Safari). However when I try to save to  Offline pdf version the figure sizes change and i can only see the middle figure taking up lots of space (even going out of the slide). Is this a known bug?

The code is currently in private repo (can't share the figures) but I could try to put up a similar slide with different figures if that helps.

Thank you
MR

---?color=#B8DDDE
@title[Workflow-1]
@snap[west]
<center>
![fig_comparison](assets/images/fig1.png)
</br>
@css[orange-60perc](**1**)
</center>
@snapend
@snap[midpoint]
<center>
![fig_comparison](assets/images/fig2.png)
</br>
@css[blue-60perc](**2**)
</center>
@snapend
@snap[east]
<center>
![fig_comparison](assets/images/fig3.png)
</br>
@css[green-60perc](**3**)
</center>
@snapend

**Comment by gitpitch** [comment] 2018-08-31 11:46
Matteo, if you can recreate the issue within a public presentation and share a link I will take a look.

**Comment by mrava87** [comment] 2018-08-31 11:57
Will do as soon as possible :)

iMR

**Comment by gitpitch** [comment] 2018-08-31 12:54
Btw, I've been looking more closely at this and I'm wondering if the issue is being caused by your use of the `<center>` tag. Which I don't recommend. I believe it has been deprecated too. When you want to control alignment I recommend using a custom css rule. 

For example, you could try:

```
.centered-content {
  text-align: center !important;
}
```

Then delete all opening and closing `<center>` tag and activate the `centered-content` class for each snap region:

- @snap[west centered-content]
- @snap[midpoint centered-content]
- @snap[east centered-content]

In reality, the default alignment for `midpoint` is `center` so it's not really needed there.

Note, I haven't tried this out but you might want to, this might be easier than trying to recreate the problem in a new presentation. If you do try it, let me know how it goes.

**Comment by mrava87** [comment] 2018-09-01 15:10
I tried to follow your suggestion using
.centered-content {
  text-align: center !important;
}
and then 

---?color=#B8DDDE
@title[3images]
@snap[west centered-content]
![fig1](assets/images/vertical1.png)
</br>
@css[gold](**Fig1**)
@snapend
@snap[midpoint centered-content]
![fig1](assets/images/vertical1.png)
</br>
@css[gold](**Fig2**)
@snapend
@snap[east centered-content]
![fig1](assets/images/vertical1.png)
</br>
@css[gold](**Fig3**)
@snapend

but I still get my figures to overlap when I save to offline mode. Take a look here: https://github.com/mrava87/Learning_GitPitch/blob/master/PITCHME.md

Cheers
MR

**Comment by gitpitch** [comment] 2018-09-01 15:53
For this to work I think you will need to specify explicit *width* constraints for your images. To do that is very simple, simply define a custom CSS style rule for `img` elements within your `centered-content` snap regions, like this:

```
.centered-content {
  text-align: center;
}

.centered-content img {
  width: 70%;
}
``` 

Try that out and let me know how it goes.

**Comment by mrava87** [comment] 2018-09-01 17:05
It works, thats great :)

Maybe worth adding something with 3 aligned figures in the documentation, unless i just missed it :)

**Comment by gitpitch** [comment] 2018-09-02 01:56
> Maybe worth adding something with 3 aligned figures in the documentation, unless i just missed it :)

Well the [snap layouts inline images](https://gitpitch.com/docs/layout-features/examples-inline-images/) doc does indeed demonstrate explicit sizing for inline images within snap regions. While the doc example only uses two images the principle applies regardless of the number of images.

But the important thing is that the problem you encountered is now solved. Closing out issue as resolved.

**Closed by gitpitch** 2018-09-02 01:56 UTC
