### ISSUE TITLE
Exporting to pdf does not preserve LaTeX font

### ISSUE THREAD

**Issue by boileaum** [gitpitch/gitpitch#45] opened 2017-02-20 16:18 UTC
See for example the difference between the proper [gitpitch rendering](https://gitpitch.com/boileaum/gitpitch/dev?grs=gitlab&t=white#) and the non math fonts of the [corresponding pdf export](https://gitpitch.com/pitchme/print/gitlab/boileaum/gitpitch/dev/white/PITCHME.pdf).

- System Version: macOS 10.12.3 (16D32)
- Kernel Version: Darwin 16.4.0
- Tested browsers:
  - Chrome Version 56.0.2924.87 (64-bit)
  - Safari Version 10.0.3 (12602.4.8)
  - Firefox Version 51.0.1 (64 bits)

**Comment by gitpitch** [comment] 2017-02-20 16:30
Hi @boileaum thanks for reporting this issue. Looks like it might be a duplicate of #13. The issue is caused by a font config problem on the GitPitch.com Ubuntu server. I've not yet been able to find a config that works when printing MathJax through [decktape](https://github.com/astefanutti/decktape).

Issue #13 has a suggested workaround if you want your PDF to look it's best, run a local copy of the GitPitch server on OSX and print from there.

**Comment by gitpitch** [comment] 2017-02-23 04:57
Hi @boileaum just fyi, a new printing option is now available on all GitPitch presentations giving you the ability to try and print directly within the browser. The new print options are presented as follows:

![gitpitch-printing](https://cloud.githubusercontent.com/assets/19169584/23244929/38cc8d5c-f9bb-11e6-93c5-b43c79d41dc6.png)

The `Generate PDF on Server` is the original print support. The `Generate PDF in Browser` is new and is available to you if you are viewing your presentation in Chrome. When you select this print option a new browser window will open. Don't worry if the rendering in the new window looks odd, the applied styling is only to support PDF generation. In the newly opened browser window do the following:

1. Open the in-browser print dialog (CTRL/CMD+P).
1. Change the **Destination** setting to **Save as PDF**.
1. Change the **Layout** to **Landscape**.
1. Change the **Margins** to **None**.
1. Enable the **Background graphics** option.
1. Click **Save**.

Here is a sample GitPitch that demonstrates many uses of MathJax formulas:

```
https://gitpitch.com/gitpitch/feature-demo/mathjax
```

The generated PDF using the new `Generate PDF in Browser` feature for this presentation can be seen here: [feature-demo_mathjax-live.pdf](https://github.com/gitpitch/gitpitch/files/795543/feature-demo_mathjax-live.pdf). You can see that the math fonts are now in use within the PDF.

There still seems to be an issue with printing your own test presentation, in fact your specific formula. The rendering must differ somehow from those formulas in the [sample presentation linked above](https://gitpitch.com/gitpitch/feature-demo/mathjax). I don't understand why yet.

Anyway, depending on what you're doing the new print feature should give you better looking PDFs for some if not yet all math formulas.

**Comment by gitpitch** [comment] 2017-06-25 08:10
Hi @boileaum a fix has just been pushed for the `Generate PDF in Browser` feature that should address all of the issues raised on this thread, including solving the outstanding problem printing the sample presentation with MathJax formulas that you provided.

Now closing this issue as resolved.

**Closed by gitpitch** 2017-06-25 08:10 UTC

**Comment by boileaum** [comment] 2017-07-03 08:00
Great, thank you! I may now advertise gitpitch to my coworkers (who are mathematicians)!
As soon as I have time for it, I will test a private instance of gitpitch in our lab.
