### ISSUE TITLE
slow to update

### ISSUE THREAD

**Issue by tuxedogold** [gitpitch/gitpitch#73] opened 2017-06-02 13:32 UTC
love git pitch and love the idea. UX frustration I have is when making changes, I make them rapidly and test, like any other coding. the issue is that it takes a few minutes at minimum to update to git-pitch, making the slide building process painful if you're doing anything with more complex markdown.  Is there a simple way to view or preview the content in real time?

**Comment by gitpitch** [comment] 2017-06-02 15:11
Hi @tuxedogold really glad you are enjoying using GitPitch and thanks for your feedback.

So if you are experiencing a delay of a couple of minutes before seeing your changes reflected in your online presentation then I suspect you are developing your presentation in your **master** branch. If you developed your presentation in a **feature** branch (any branch other than master) then you would see your updates almost instantly. The reason for this is explained on by the [GitPitch Caching Policy](https://github.com/gitpitch/gitpitch/wiki/GitPitch-Caching) page in the Wiki.

Personally, I always develop in a feature branch and then simply merge the final result into master when I'm ready to publish/share etc.

You do however have one more option which is to develop locally. You can find details on how to do that using GitPitch on the [Develop / Testing Locally](https://github.com/gitpitch/gitpitch/wiki/Developing-Testing-Locally) page in the Wiki.

Hopefully one or both of these options will make things better or you as you develop your presentations.

**Comment by gitpitch** [comment] 2017-06-09 15:59
Assuming issue caused by developing presentation content in `master`. Issue explained and resolved by  caching policy and `feature-branch` best practices. Closing this issue as resolved.

**Closed by gitpitch** 2017-06-09 15:59 UTC
