### ISSUE TITLE
Issue with Code Fragment Highlighting

### ISSUE THREAD

**Issue by terrywbrady** [gitpitch/gitpitch#74] opened 2017-06-04 04:10 UTC
I am returning back to GitPitch, and I see that you have added several great features to re-use code assets.  The new transition and fragment syntax is awesome.

In the following presentation: https://gitpitch.com/terrywbrady/tbDemo/test

I am seeing inconsistencies in the code fragment highlighting feature.
* Slide 2.4 does exactly what I want with code fragments
* Slide 2.3 displays fine until I reference fragments.  The fragments are dimly hightlighted
* Slide 4.2 has the same issue

I attempted a few work arounds assuming there was something in my code files triggering the issue, but I am stuck on how to resolve the issue.

**Comment by gitpitch** [comment] 2017-06-04 08:59
Hi @terrywbrady good to hear from you. The issue you are facing here results from an attempt to embed HTML code (header.php) within a HTML page (your presentation) without first escaping the HTML content to be embedded. 

To embed HTML inside a code block (which is what happens using code-presenting) you need to escape all angle brackets: < and >.

I tried that by making a fork of your presentation and escaping all angle brackets. You can see the [result here](https://gitpitch.com/terrywbrady/tbDemo/test). It's better. But this issue is not fully fixed. Because the escaped content (brackets) are not be converted back to brackets for rendering on the slide.

So I can understand the cause of the problem you have reported but I don't have a full solution for you right now. I'll look into this further (hopefully tomorrow) and get back to you once I know more.

**Comment by gitpitch** [comment] 2017-06-04 13:10
@terrywbrady I've just submitted a [PR on your test repo](https://github.com/terrywbrady/tbDemo/pull/1) that incorporates a workaround to the HTML escaping issue reported on this thread. This workaround simply wraps the markup files you are importing within a CDATA block to prevent that content being parsed/rendered as page content.

A complete solution within GP would obviate the need for this CDATA block. That is something I will look into. This PR should give you a temporary solution to keep you moving ahead building your presentation.

**Comment by gitpitch** [comment] 2017-06-07 14:08
A few days ago I gave you a workaround to the rendering issue you reported on this thread. Now I have a fix for you and that fix is live on gitpitch.com and you can make the necessary changes to your repo to avail of the fix.

### The Fix
A new option is now supported on code delimiters. That option allows you to provide a language hint to GitPitch (and the [highlight.js library](https://highlightjs.org) used by GitPitch) so it knows how to best to render your code (or HTML, XML, etc). The language hint ensures that the correct escaping is applied (if any) for your source code when being rendered into the presentation.
```
---?code=path/to/source.file&lang=language-alias
```

The `&lang=` is a new option on the code-delimiter. And `language-alias` is a `highlight.js` library alias that identifies a language type. Further described below.

### The Steps
@terrywbrady you need to take the following steps to resolve this issue:

1. Remove the opening and closing CDATA tags that my PR added to your `header.php` and `03_ShowObject.php` files
2. Update the CF-marker line indexes to match the new content in these files
3. Update the code delimiters for these files as follows:

Replace:

```
+++?code=Pages/header.php
...
+++?code=Pages/03_ShowObject.php
```

With this:

```
+++?code=Pages/header.php&lang=php
...
+++?code=Pages/03_ShowObject.php&lang=php
```

### The Background

As mentioned above, GitPitch uses the `highlight.js` library to render syntax highlighted code. The language type `php` that I am using here is taken from the list of [highlight.js language aliases documented here](http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html?highlight=language%20class#language-names-and-aliases).

I have not yet had time to update the [code delimiter slides](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides) page on the Wiki but hopefully you have enough here to fix this issue.

Please let me know how you get on so we can make a decision as to whether or not we can close out this issue. Thanks.

**Comment by terrywbradyC9** [comment] 2017-06-07 16:59
@gitpitch , this works beautifully for me.

So far, I have just fixed my existing files.  I will be creating more elaborate samples soon, and this will be especially helpful as the files get larger.  The ability to annotate sections as they are highlighted is awesome.

Thank you.

**Comment by gitpitch** [comment] 2017-06-08 00:46
Great @terrywbrady glad this fixed your problem and you are enjoying the new code-presenting feature. Closing this issue as resolved.

**Closed by gitpitch** 2017-06-08 00:46 UTC

**Comment by gitpitch** [comment] 2017-06-08 02:38
For any future visitors to this thread, just updating here with a link to the [new documentation on the Wiki](https://github.com/gitpitch/gitpitch/wiki/Code-Delimiter-Slides#code-highlighting-language-hint) for working with _language-hints_ when using code-delimiters.
