### ISSUE TITLE
Task Lists are not shown 

### ISSUE THREAD

**Issue by akarsh** [gitpitch/gitpitch#75] opened 2017-06-09 10:45 UTC
I am not able to see task lists in the slides.
Following the the markdown on how to show ![Task Lists](https://guides.github.com/features/mastering-markdown/)
In the github it works as expected. But, it in the slides it is not the same.
Here is out ![PITCHME.md](https://github.com/akarsh/TUPJNOSQL17/blob/master/PITCHME.md) file

Help appreciated.

Thank you

**Comment by gitpitch** [comment] 2017-06-09 10:58
Hi @akarsh I'm going to close this issue as a duplicate of #67. The short answer, task lists are a feature of the GitHub service, not of GitHub-flavored markdown. So they are not supported by GitPitch.

**Closed by gitpitch** 2017-06-09 10:58 UTC

**Comment by akarsh** [comment] 2017-06-09 11:38
Okay 
I will use GFM editor. I was using preview feature of github to see the style.
I will skip Task Lists.
Thanks @gitpitch
